export const NAV = {
  resident: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/resident/dashboard" },
    { label: "My Health Record", icon: "FileHeart", path: "/app/resident/record" },
    { label: "Appointments", icon: "CalendarDays", path: "/app/resident/appointments" },
    { label: "Health Services", icon: "Stethoscope", path: "/app/resident/services" },
    { label: "Notifications", icon: "Bell", path: "/app/resident/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/resident/settings" },
  ],
  bhw: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/bhw/dashboard" },
    { label: "Residents", icon: "Users", path: "/app/bhw/residents" },
    { label: "Verifications", icon: "ShieldCheck", path: "/app/bhw/verifications" },
    { label: "Household Profiling", icon: "Home", path: "/app/bhw/households" },
    { label: "Follow-up", icon: "CalendarClock", path: "/app/bhw/followup" },
    { label: "Consultations", icon: "Stethoscope", path: "/app/bhw/consultations" },
    { label: "Reports", icon: "BarChart3", path: "/app/bhw/reports" },
    { label: "Notifications", icon: "Bell", path: "/app/bhw/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/bhw/settings" },
  ],
  midwife: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/midwife/dashboard" },
    { label: "Consultations", icon: "Stethoscope", path: "/app/midwife/consultations" },
    { label: "Residents", icon: "Users", path: "/app/midwife/residents" },
    { label: "TCLS", icon: "ClipboardList", path: "/app/midwife/tcls" },
    { label: "M1 Records", icon: "FileHeart", path: "/app/midwife/m1" },
    { label: "Follow-ups", icon: "CalendarClock", path: "/app/midwife/followups" },
    { label: "Health Services", icon: "Activity", path: "/app/midwife/services" },
    { label: "Immunization", icon: "Syringe", path: "/app/midwife/immunization" },
    { label: "Referrals", icon: "Send", path: "/app/midwife/referrals" },
    { label: "Reports", icon: "BarChart3", path: "/app/midwife/reports" },
    { label: "Notifications", icon: "Bell", path: "/app/midwife/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/midwife/settings" },
  ],
  rhu: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/rhu/dashboard" },
    { label: "Residents", icon: "Users", path: "/app/rhu/residents" },
    { label: "Barangays", icon: "Map", path: "/app/rhu/barangays" },
    { label: "Reports", icon: "FileText", path: "/app/rhu/reports" },
    { label: "Health Programs", icon: "HeartPulse", path: "/app/rhu/programs" },
    { label: "Settings", icon: "Settings", path: "/app/rhu/settings" },
  ],
  mho: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/mho/dashboard" },
    { label: "Analytics", icon: "BarChart3", path: "/app/mho/analytics" },
    { label: "Barangays", icon: "Map", path: "/app/mho/barangays" },
    { label: "Reports", icon: "FileText", path: "/app/mho/reports" },
    { label: "Health Programs", icon: "HeartPulse", path: "/app/mho/programs" },
    { label: "Settings", icon: "Settings", path: "/app/mho/settings" },
  ],
  admin: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/admin/dashboard" },
    { label: "User Management", icon: "Users", path: "/app/admin/users" },
    { label: "Roles", icon: "Shield", path: "/app/admin/roles" },
    { label: "Permissions", icon: "KeyRound", path: "/app/admin/permissions" },
    { label: "Audit Trail", icon: "ScrollText", path: "/app/admin/audit" },
    { label: "System Settings", icon: "Settings", path: "/app/admin/settings" },
    { label: "Logs", icon: "Terminal", path: "/app/admin/logs" },
  ],
};