export const NAV = {
  "resident-limited": [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/resident-limited/dashboard" },
    { label: "Health Services", icon: "Stethoscope", path: "/app/resident-limited/services" },
    { label: "Notifications", icon: "Bell", path: "/app/resident-limited/announcements" },
    { label: "Profile", icon: "User", path: "/app/resident-limited/profile" },
    { label: "Settings", icon: "Settings", path: "/app/resident-limited/settings" },
    { label: "My Health Records", icon: "FileHeart", path: "#", locked: true },
    { label: "Consultation History", icon: "ClipboardList", path: "#", locked: true },
    { label: "Follow-ups", icon: "CalendarClock", path: "#", locked: true },
  ],
  resident: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/resident/dashboard" },
    { label: "My Health Records", icon: "FileHeart", path: "/app/resident/record" },
    { label: "Consultation History", icon: "ClipboardList", path: "/app/resident/consultations" },
    { label: "Follow-ups", icon: "CalendarClock", path: "/app/resident/followups" },
    { label: "Health Services", icon: "Stethoscope", path: "/app/resident/services" },
    { label: "Notifications", icon: "Bell", path: "/app/resident/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/resident/settings" },
  ],
  bhw: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/bhw/dashboard" },
    { label: "Residents", icon: "Users", path: "/app/bhw/residents" },
    { label: "Verifications", icon: "ShieldCheck", path: "/app/bhw/verifications" },
    { label: "Household Profiling", icon: "Home", path: "/app/bhw/households" },
    { label: "Follow-up", icon: "CalendarClock", path: "/app/bhw/followup" },
    { label: "Reports", icon: "BarChart3", path: "/app/bhw/reports" },
    { label: "Notifications", icon: "Bell", path: "/app/bhw/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/bhw/settings" },
  ],
  midwife: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/midwife/dashboard" },
    { label: "Treatment Consultation", icon: "Stethoscope", path: "/app/midwife/consultations" },
    { label: "Residents", icon: "Users", path: "/app/midwife/residents" },
    { label: "Records", icon: "ClipboardList", children: [
      { label: "TCLS", icon: "ClipboardList", path: "/app/midwife/tcls" },
      { label: "M1", icon: "FileHeart", path: "/app/midwife/m1" },
    ] },
    { label: "Follow-ups", icon: "CalendarClock", path: "/app/midwife/followups" },
    { label: "Health Services", icon: "Activity", path: "/app/midwife/services" },
    { label: "Immunization", icon: "Syringe", path: "/app/midwife/immunization" },
    { label: "Referrals", icon: "Send", path: "/app/midwife/referrals" },
    { label: "Reports", icon: "BarChart3", path: "/app/midwife/reports" },
    { label: "Notifications", icon: "Bell", path: "/app/midwife/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/midwife/settings" },
  ],
  rhu: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/rhu/dashboard" },
    { label: "Residents", icon: "Users", path: "/app/rhu/residents" },
    { label: "Barangays", icon: "Map", path: "/app/rhu/barangays" },
    { label: "Reports", icon: "FileText", path: "/app/rhu/reports" },
    { label: "Health Programs", icon: "HeartPulse", path: "/app/rhu/programs" },
    { label: "Settings", icon: "Settings", path: "/app/rhu/settings" },
  ],
  mho: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/mho/dashboard" },
    { label: "Health Trends", icon: "TrendingUp", path: "/app/mho/trends" },
    { label: "Referrals", icon: "Send", path: "/app/mho/referrals" },
    { label: "Notifications", icon: "Bell", path: "/app/mho/notifications" },
    { label: "Settings", icon: "Settings", path: "/app/mho/settings" },
  ],
  admin: [
    { label: "Dashboard", icon: "LayoutDashboard", path: "/app/admin/dashboard" },
    { label: "User Management", icon: "Users", path: "/app/admin/users" },
    { label: "Roles", icon: "Shield", path: "/app/admin/roles" },
    { label: "Permissions", icon: "KeyRound", path: "/app/admin/permissions" },
    { label: "Audit Trail", icon: "ScrollText", path: "/app/admin/audit" },
    { label: "System Settings", icon: "Settings", path: "/app/admin/settings" },
    { label: "Logs", icon: "Terminal", path: "/app/admin/logs" },
  ],
};