import React, { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertCircle, ArrowLeft, ArrowRight, Check, Loader2, ShieldCheck } from "lucide-react";
import {
  RegistrationShell, RegistrationCard, StepIndicator, PageHeading, InfoNote, btnPrimary, btnGhost,
} from "@/features/registration/components/RegistrationDesign";
import UploadComponent from "@/features/registration/components/UploadComponent";
import { supabase } from "@/lib/supabase";
import { api } from "@/services/api";
import { postFormData } from "@/services/api/apiClient";

const STEPS = [
  { num: 1, label: "Account" },
  { num: 2, label: "Documents" },
  { num: 3, label: "Submit" },
];
// Transfer of Residency OTP length. This is a custom 4-digit code generated by
// the KALUSAGAP backend (see backend transfer.service.js) and is intentionally
// separate from the 6-digit Supabase Auth registration OTP. Do not merge these.
const TRANSFER_OTP_LENGTH = 4;
const DOCUMENTS = [
  { key: "government_id_front", label: "Government ID - Front" },
  { key: "government_id_back", label: "Government ID - Back" },
  { key: "transfer_previous_health_record", label: "Previous Health Record" },
  { key: "transfer_proof_of_address", label: "Proof of New Address in Pili" },
];

function OtpInput({ value, onChange }) {
  const refs = useRef([]);
  const digits = value.padEnd(TRANSFER_OTP_LENGTH, "").slice(0, TRANSFER_OTP_LENGTH).split("");
  const update = (index, next) => {
    const nextDigits = [...digits];
    nextDigits[index] = next.replace(/\D/g, "").slice(-1);
    onChange(nextDigits.join(""));
    if (nextDigits[index] && index < TRANSFER_OTP_LENGTH - 1) refs.current[index + 1]?.focus();
  };
  const paste = (event) => {
    event.preventDefault();
    const clean = (event.clipboardData.getData("text") || "").replace(/\D/g, "").slice(0, TRANSFER_OTP_LENGTH);
    onChange(clean);
    refs.current[Math.min(TRANSFER_OTP_LENGTH - 1, clean.length)]?.focus();
  };
  return (
    <div className="flex gap-2" onPaste={paste}>
      {digits.map((digit, index) => (
        <input
          key={index}
          ref={(element) => { refs.current[index] = element; }}
          value={digit}
          inputMode="numeric"
          maxLength={1}
          aria-label={`Verification digit ${index + 1}`}
          onChange={(event) => update(index, event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Backspace" && !digits[index] && index > 0) refs.current[index - 1]?.focus();
            if (event.key === "ArrowLeft" && index > 0) refs.current[index - 1]?.focus();
            if (event.key === "ArrowRight" && index < TRANSFER_OTP_LENGTH - 1) refs.current[index + 1]?.focus();
          }}
          className="h-14 w-12 rounded-xl border border-slate-200 bg-slate-50 text-center text-xl font-bold text-brand-ink outline-none focus:border-brand-blue focus:ring-4 focus:ring-brand-blue/10"
        />
      ))}
    </div>
  );
}

export default function TransferRegistration() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [otp, setOtp] = useState("");
  const [requestId, setRequestId] = useState("");
  const [resendAfter, setResendAfter] = useState(0);
  const [now, setNow] = useState(Date.now());
  const [documents, setDocuments] = useState({});
  const [governmentIdType, setGovernmentIdType] = useState("philsys");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!resendAfter) return undefined;
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, [resendAfter]);

  const message = (err) => err?.message || "We could not complete this step. Please try again.";
  const signIn = async () => {
    if (!email.trim() || !password) return setError("Enter your email address and password.");
    setBusy(true); setError("");
    try {
      if (!supabase) throw new Error("Authentication is unavailable. Please try again later.");
      const { error: authError } = await supabase.auth.signInWithPassword({ email: email.trim(), password });
      if (authError) throw authError;
      const response = await api.post("/transfer-requests/otp", {});
      setRequestId(response.requestId); setResendAfter(Date.now() + 60000); setStep(2);
    } catch (err) { setError(message(err)); }
    finally { setBusy(false); }
  };
  const verify = async () => {
    if (!/^\d{4}$/.test(otp)) return setError("Enter the four-digit verification code.");
    setBusy(true); setError("");
    try { await api.post("/transfer-requests/otp/verify", { requestId, otp }); setStep(3); }
    catch (err) { setError(message(err)); }
    finally { setBusy(false); }
  };
  const resend = async () => {
    if (Date.now() < resendAfter) return;
    setBusy(true); setError("");
    try { const response = await api.post("/transfer-requests/otp", {}); setRequestId(response.requestId); setOtp(""); setResendAfter(Date.now() + 60000); }
    catch (err) { setError(message(err)); }
    finally { setBusy(false); }
  };
  const upload = async (key, file) => {
    if (!file) return;
    setBusy(true); setError("");
    try {
      const form = new FormData(); form.append("file", file); form.append("documentType", key);
      if (key.startsWith("government_id")) form.append("governmentIdType", governmentIdType);
      const response = await postFormData(`/transfer-requests/${requestId}/documents`, form);
      setDocuments((current) => ({ ...current, [key]: { file, document: response.document } }));
    } catch (err) { setError(message(err)); }
    finally { setBusy(false); }
  };
  const submit = async () => {
    setBusy(true); setError("");
    try { await api.post(`/transfer-requests/${requestId}/submit`, {}); setStep(5); }
    catch (err) { setError(message(err)); }
    finally { setBusy(false); }
  };
  const allDocuments = DOCUMENTS.every(({ key }) => documents[key]);
  const countdown = Math.max(0, Math.ceil((resendAfter - now) / 1000));
  const currentStage = step >= 5 ? 4 : step >= 4 ? 3 : step >= 3 ? 2 : 1;

  return (
    <RegistrationShell>
      <RegistrationCard>
        <div className="px-5 py-6 sm:px-10 sm:py-8">
          <StepIndicator current={currentStage} steps={STEPS} flowLabel="Transfer of Residency" showStepCount={false} />
          <div className="mt-6 space-y-5">
            {error && <InfoNote tone="danger" icon={AlertCircle}>{error}</InfoNote>}
            {step === 1 && <>
              <PageHeading title="Sign in to your KALUSAGAP account" subtitle="Sign in using the account associated with your existing KALUSAGAP resident record." />
              <div className="space-y-4">
                <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500">Email Address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" autoComplete="email" /></label>
                <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500">Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" autoComplete="current-password" /></label>
              </div>
              <Link to="/login" className="inline-block text-xs font-semibold text-brand-blue underline">Forgot Password?</Link>
              <InfoNote icon={ShieldCheck}>Your account must be authenticated before a transfer request can begin. Resident records are never searchable from this flow.</InfoNote>
            </>}
            {step === 2 && <>
              <PageHeading title="Verify your transfer request" subtitle="We sent a 4-digit verification code to your registered email address." />
              <OtpInput value={otp} onChange={setOtp} />
              <button type="button" onClick={resend} disabled={busy || countdown > 0} className="text-left text-xs font-semibold text-brand-blue disabled:text-slate-400">{countdown > 0 ? `Resend in 00:${String(countdown).padStart(2, "0")}` : "Didn't receive the code? Resend OTP"}</button>
            </>}
            {step === 3 && <>
              <PageHeading title="Upload required documents" subtitle="Provide the documents needed to verify your transfer of residency." />
              <InfoNote icon={ShieldCheck}>Documents are stored in KALUSAGAP&apos;s private document bucket and are visible only to you and authorized reviewers.</InfoNote>
              <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500">Government ID type<select value={governmentIdType} onChange={(event) => setGovernmentIdType(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><option value="philsys">PhilSys / National ID</option><option value="drivers_license">Driver&apos;s License</option><option value="passport">Passport</option><option value="umid">UMID</option><option value="postal_id">Postal ID</option></select></label>
              <div className="space-y-4">{DOCUMENTS.map(({ key, label }) => <div key={key}><UploadComponent label={label} file={documents[key]?.file || null} onFile={(file) => upload(key, file)} onRemove={() => setDocuments((current) => { const next = { ...current }; delete next[key]; return next; })} />{documents[key] && <p className="mt-1 text-xs font-semibold text-emerald-700"><Check className="mr-1 inline h-3.5 w-3.5" />Uploaded - pending review</p>}</div>)}</div>
            </>}
            {step === 4 && <>
              <PageHeading title="Review and submit" subtitle="Review the documents attached to your authenticated account before submitting." />
              <div className="divide-y divide-slate-100 rounded-xl border border-slate-200"><p className="px-4 py-3 text-sm text-brand-ink"><strong>Account:</strong> {email}</p>{DOCUMENTS.map(({ key, label }) => <p key={key} className="px-4 py-3 text-sm text-brand-ink"><Check className="mr-2 inline h-4 w-4 text-emerald-600" />{label}</p>)}</div>
            </>}
            {step === 5 && <>
              <PageHeading title="Transfer request submitted" subtitle="Your request has been submitted successfully. Your documents will be reviewed by authorized personnel." />
              <InfoNote icon={ShieldCheck}><strong className="block text-brand-dark">PENDING VERIFICATION</strong><span className="mt-1 block">You will receive a notification when your transfer request has been reviewed.</span></InfoNote>
            </>}
          </div>
          <div className="mt-8 flex items-center justify-between gap-3 border-t border-slate-100 pt-5">
            {step < 5 ? <Link to="/register" className={btnGhost}><ArrowLeft className="h-4 w-4" /> Back</Link> : <span />}
            {step === 1 && <button onClick={signIn} disabled={busy} className={btnPrimary}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}Sign In <ArrowRight className="h-4 w-4" /></button>}
            {step === 2 && <button onClick={verify} disabled={busy} className={btnPrimary}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}Verify <ArrowRight className="h-4 w-4" /></button>}
            {step === 3 && <button onClick={() => allDocuments && setStep(4)} disabled={!allDocuments || busy} className={btnPrimary}>Continue <ArrowRight className="h-4 w-4" /></button>}
            {step === 4 && <button onClick={submit} disabled={busy} className={btnPrimary}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}Submit Transfer Request <ArrowRight className="h-4 w-4" /></button>}
            {step === 5 && <button onClick={() => navigate("/app/resident")} className={btnPrimary}>Go to Dashboard <ArrowRight className="h-4 w-4" /></button>}
          </div>
        </div>
      </RegistrationCard>
    </RegistrationShell>
  );
}
