-- KALUSAGAP - Health Supervisor referral coordination
--
-- Adds public.health_referrals: the barangay-scoped operational referral
-- coordination workflow used by the Health Supervisor (and PHN) to refer a
-- resident to the RHU / a higher-level facility or service and track its
-- status through to completion.
--
-- WHY A NEW TABLE (not public.referrals):
--   public.referrals (migration 1) is the RHU *referral document* generated by
--   the PHN from a specific visit (visit_id NOT NULL + unique, frozen patient/
--   visit snapshots, PHN-only RLS, REF- text ids). It is a different concept,
--   is already wired to a working workflow (/api/phn/referrals), and is NOT
--   barangay-scoped. Reusing/rewriting it would break that workflow and cannot
--   satisfy the barangay-scoped access rule required here, so this migration
--   adds a distinct, resident-linked, barangay-scoped table instead. No
--   existing table, row, policy or trigger is modified or removed.
--
-- Additive only. Scope columns (municipality_id, barangay_id) are copied from
-- the resident by the shared public.sync_operational_scope() trigger, so a
-- caller can never place a referral in a barangay they do not cover by sending
-- an arbitrary id.

begin;

create table public.health_referrals (
  id uuid primary key default gen_random_uuid(),
  resident_id text not null references public.residents(id) on delete restrict,
  municipality_id uuid references public.municipalities(id) on delete restrict,
  barangay_id uuid references public.barangays(id) on delete restrict,
  referring_facility text not null default '',
  reason text not null default '',
  destination_facility text not null default '',
  destination_service text not null default '',
  priority text not null default 'Medium' check (priority in ('Low', 'Medium', 'High')),
  status text not null default 'Pending' check (status in ('Pending', 'Accepted', 'In Progress', 'Completed', 'Cancelled')),
  referral_date date not null default current_date,
  notes text not null default '',
  resolution_notes text not null default '',
  completed_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Scope is derived from the resident, never trusted from the caller.
create trigger health_referrals_scope
  before insert or update on public.health_referrals
  for each row execute function public.sync_operational_scope();

create trigger health_referrals_updated
  before update on public.health_referrals
  for each row execute function public.set_updated_at();

create index health_referrals_scope_idx on public.health_referrals(barangay_id, status);
create index health_referrals_resident_idx on public.health_referrals(resident_id);
create index health_referrals_date_idx on public.health_referrals(referral_date desc);

-- ---------------------------------------------------------------------------
-- Row Level Security — mirrors the operational-records boundary exactly:
--   admin                       -> all
--   mho / phn / rhu_personnel   -> own municipality
--   health_supervisor / bhw     -> own assigned barangay only
--   resident                    -> only referrals linked to their own account
-- ---------------------------------------------------------------------------
alter table public.health_referrals enable row level security;

create policy health_referrals_select on public.health_referrals
  for select to authenticated
  using (
    public.is_admin() or (
      public.is_staff_active() and (
        (public.profile_role() in ('mho', 'phn', 'rhu_personnel') and municipality_id = public.profile_municipality_id())
        or (public.profile_role() in ('health_supervisor', 'bhw') and barangay_id = public.profile_barangay_id())
      )
    ) or exists (
      select 1 from public.residents r
      where r.id = health_referrals.resident_id and r.auth_user_id = auth.uid()
    )
  );

create policy health_referrals_insert on public.health_referrals
  for insert to authenticated
  with check (
    public.is_staff_active() and public.profile_covers_barangay(barangay_id)
  );

create policy health_referrals_update on public.health_referrals
  for update to authenticated
  using (
    public.is_admin() or (public.is_staff_active() and public.profile_covers_barangay(barangay_id))
  )
  with check (
    public.is_admin() or (public.is_staff_active() and public.profile_covers_barangay(barangay_id))
  );

create policy health_referrals_delete on public.health_referrals
  for delete to authenticated
  using (
    public.is_admin() or (public.is_staff_active() and public.profile_covers_barangay(barangay_id))
  );

commit;
