// New Resident Registration email OTP helpers.
//
// This OTP is generated by Supabase Auth (the "Confirm Signup" email {{ .Token }})
// and verified via supabase.auth.verifyOtp({ type: "email" }). It is intentionally
// SEPARATE from the Transfer of Residency OTP (a custom 4-digit backend code). Do
// not share this constant, state, or validation with the transfer flow.
//
// The code is always handled as a STRING so leading zeros (e.g. "012345") are
// preserved and never coerced to a Number.
export const REGISTRATION_OTP_LENGTH = 6;

const REGISTRATION_OTP_PATTERN = new RegExp(`^\\d{${REGISTRATION_OTP_LENGTH}}$`);

/**
 * Keep only digits and cap the length so paste/typing cannot exceed the expected
 * OTP length. Returns a string; leading zeros are preserved.
 * @param {unknown} value
 * @returns {string}
 */
export const sanitizeRegistrationOtp = (value) =>
  String(value ?? "").replace(/\D/g, "").slice(0, REGISTRATION_OTP_LENGTH);

/**
 * True only when the value is exactly REGISTRATION_OTP_LENGTH numeric digits.
 * The value is compared as a string, so "012345" is valid.
 * @param {unknown} value
 * @returns {boolean}
 */
export const isValidRegistrationOtp = (value) =>
  REGISTRATION_OTP_PATTERN.test(String(value ?? ""));
